### PR TITLE
Some mods

### PR DESCRIPTION
**Pull request by flametaichou**
I added textures for these mods:
- Backpack 
- Chest Transporter
- Cosmetic Armor
- Dragon's Radio Mod 
- Enchvil
- Gany's Surface 
- HariboteAirCraft 
- KeyAndCodeLockMod
- Level Up! Mod	
- MoreBows2
- Primitive Mobs v1.0	
- RPG_Hud or Interface+ 
- Trapcraft

### CODE REVIEW

**Comment by ScottKillen** [comment]
Are these textures original to you? What are there source?

**Comment by flametaichou** [comment]
All textures, except for backpacks, key, chocolate cake, and bows, original to me. I just recolored bows (from Atherys Ascended and Conquest), backpacks were taken from faithful (I think, they are matches to JS style), but I edited workbench and ender backpacks and repainted gui and leather textures. Chocolate cake was taken from Conquest. Key was taken from JSTR mocreatures, recolored.

**Comment by ScottKillen** [comment]
Unfortunately, we can't include any textures from other packs. Please remove the Faithful and Conquest textures. Some of the files in Gany's Surface look like Faithful textures also. (Specifically the poop blocks.) Please make sure that everything is either sourced from elsewhere in JSTR or your own textures.

**Comment by Oddface** [comment]
Faithful 32 Modded license:
"You may use modify this pack in any way you see fit. You may not profit from its distribution or the distribution of derivatives."

So it's okay to use those. But the Conquest textures need to go.
Other than that, nice work!

**Comment by ScottKillen** [comment]
Oh...sorry, I was looking at the Faithful vanilla terms which specifically requires its textures to be released as faithful add ons. 👍

**Comment by ScottKillen** [comment]
And yes, @flametaichou nice job on these.

**Comment by flametaichou** [comment]
I created a new pull request https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/pull/173
So this one can be closed

**Comment by ScottKillen** [comment]
Closed per @flametaichou

**Pull request closed without merging**
