### PR TITLE
Create Aether

### PR DESCRIPTION
**Pull request by EdwardFlyhieght**
I'm new to githube and not sure how to get it working. I've been working on a Aether 2 john smith pack. i would like to try to add it but not shure how this all works

### CODE REVIEW

**Comment by ScottKillen** [comment]
You did it! :+1:

**Comment by EdwardFlyhieght** [comment]
so from here someone will push it forward into the pack?

**Comment by ScottKillen** [comment]
They will review and offer feedback if needed and when all is well it will be pulled into the pack from your repository.

**Comment by Oddface** [comment]
This pull request only has a folder. The textures are not actually in it.
The textures look good, though. The ores and stone don't look like they match, so maybe fix that. For the white rose there is a rose texture in the Biomes o Plenty patch you can use instead of the poppy texture you're using now.

**Comment by EdwardFlyhieght** [comment]
yea confusing. that is actually from the first time i tried to upload the
folder i had closed and deleted it. and started over and somehow it stayed
on git hub and wouldn't let me up load the current the aether is more a
test if i can get this to work I've mad many more textures like the clear
glass fix i did a long time ago ( i did see some one did fix it) I made a
forestry treealizer gui, i fixed the Applied_Energistics_2
MolecularAssemblerLights. i just want to see if u guys are accepting of my
work before i load any more. The aether does need some work and rework but
i just want to get a start on it. and get my bearings for gethub. so if you
can go ahead and delete the pull request so i can try starting from fresh.
i would appreciate it

**Comment by Oddface** [comment]
Alright.

**Pull request closed without merging**
